services:

  postgres:
    image: postgres:13.4
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "card-db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork
  
  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761" # Port Eureka
    networks:
      - mynetwork
    depends_on:
      - postgres

  reverse-proxy:
    build: ./reverse-proxy
    container_name: reverse-proxy
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    depends_on:
      - discovery-service

  request-management-service:
    build: ./request-management-service
    container_name: request-management-service
    ports:
      - "7070:7070" 
    networks:
      - mynetwork
    depends_on:
      - discovery-service
  
  
  text-generation-service:
    build: ./text-generation-service
    container_name: text-generation-service
    ports:
      - "8083:8083" 
    networks:
      - mynetwork
    depends_on:
      - discovery-service

  image-generation-service:
    build: ./image-generation-service
    container_name: image-generation-service
    ports:
      - "8081:8081" # Port interne 8080 mappé au port externe 8086
    networks:
      - mynetwork
    depends_on:
      - discovery-service
    
  property-service:
    build: ./property-calculation-service
    container_name: property-calculation-service
    ports:
      - "8089:8089" # Port interne 8080 mappé au port externe 8087
    networks:
      - mynetwork
    depends_on:
      - discovery-service
  
  backend-service:
    build: ./backend
    container_name: backend-service
    ports:
      - "8084:8084"
    networks:
      - mynetwork
    depends_on:
      - discovery-service
      - activemq
  
  activemq:
    image: symptoma/activemq:5.18.3
    ports:
      - "61616:61616"
      - "61613:61613"
      - "8161:8161"
    environment:
      ACTIVEMQ_DISALLOW_WEBCONSOLE: 'false'
      ACTIVEMQ_USERNAME: myuser
      ACTIVEMQ_PASSWORD: mypwd
      ACTIVEMQ_WEBADMIN_USERNAME: myuserweb
      ACTIVEMQ_WEBADMIN_PASSWORD: mypwd
    networks:
      - mynetwork

  img-gen-ln:
    image: registry.gitlab.com/js-asi2/asi2-resources/img-gene-neural-love-api:v1.1
    ports:
      - "8082:8080"
    environment:
      external.iaimgapi.token: 'v1.811d96c7bbbd148ae0b4bd54baf8abdfee0d0dbb6f2d4321e6edb49dc30f0abd'

  ollama-local:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

networks:
  mynetwork:

volumes:
  postgres_data:
  ollama:
